stages:
  - build

workflow:
    rules:
        # merge pipelines
        - if: $CI_PIPELINE_SOURCE == "merge_request_event"
        - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
          when: never
        # branch pipelines
        - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

default:
  image: python:3.11
  before_script:
  - pip install -U pdm
  - export PDM_CHECK_UPDATE=false

current_env:
  stage: build
  script:
  - pdm lock -dG :all
  - pdm install --frozen-lockfile -dG test
  - pdm run nox
  - pdm run nox -s docs
  artifacts:
    paths:
      - docs/build/*
    expire_in: 1 week

min_env:
  stage: build
  script:
  - pdm lock -dG :all --strategy direct_minimal_versions
  - pdm install --frozen-lockfile -dG test
  - pdm run nox -s test
