# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint_and_docs:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        lfs: false  # Save GitHub LFS bandwidth

    - name: Setup PDM and Python ${{ matrix.python-version }}
      uses: pdm-project/setup-pdm@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: pdm install -dG :all
    - name: Lint
      run: pdm run nox -s lint
    - name: Docs
      run: pdm run nox -s docs
